project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  #favicon: images/favicon.ico
  title: "Open Handbook Commons"
  description: "Open practical knowledge for everyone."
  site-url: https://openhandbook.org
  back-to-top-navigation: true
  navbar:
    background: dark
    foreground: light
    title: "Open Handbook Commons"
    logo: images/logo.png
    logo-alt: "Open Handbook Commons Logo"
    right:
      - text: "Library"
        file: library/index.qmd
      - text: "About"
        file: about/index.qmd
      - text: "Contribute"
        file: contribute/index.qmd
      #- text: "FAQs"
      #  file: faq/index.qmd
    left: 
      - icon: github
        href: https://github.com/openhandbookcommons

  page-footer: 
    center: |
      <p>© 2026 Open Handbook Commons · openhandbook.org</p>
      <p>Except where otherwise noted, all content is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener"> Creative Commons Attribution–NonCommercial–ShareAlike 4.0 International</a>.</p>
    background: dark
    foreground: light
 
format:
  html:
    theme: materia
    fontsize: 1.2em
    css: /css/styles.css
    #backgroundcolor: "#f4f6f8"
    link-external-icon: true
    link-external-newwindow: true
    mainfont: Libertinus Serif
    include-in-header: 
      - text: |
          <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=651f6abdc9bda500128cb0eb&product=sticky-share-buttons&source=platform" async="async"></script>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Libertinus+Serif:wght@400;600;700&display=swap" rel="stylesheet">
    include-after-body: 
      - text: |
          <div class="sharethis-sticky-share-buttons"></div>
editor: source





